{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.3"
    }
  },
  "component" : {
    "group" : "com.github.roborescue",
    "module" : "adf-core-java",
    "version" : "master-SNAPSHOT",
    "attributes" : {
      "org.gradle.status" : "integration"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "adf-core-java-master-SNAPSHOT.jar",
      "url" : "adf-core-java-master-SNAPSHOT.jar",
      "size" : 369142,
      "sha512" : "268dc76d6c2db1b9b1c54cbbf9febfd92e30c7c30753117fb82108e42501179a5d5668049ca117bd1ae2b0574873f3bf8eccd5e7d69a574999a2a974197d7f4b",
      "sha256" : "5fe29ce554d90bc278814e29e281b6e4fa1a935ec631640bc1aaf989e8615af8",
      "sha1" : "e2d8ebc437c857da19386381c516299888e94471",
      "md5" : "485d6dae40ec2e02e63fb36b0e1296a9"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.github.roborescue",
      "module" : "rcrs-server",
      "version" : {
        "requires" : "master-SNAPSHOT"
      }
    }, {
      "group" : "com.fasterxml.jackson.core",
      "module" : "jackson-annotations",
      "version" : {
        "requires" : "2.13.0"
      }
    }, {
      "group" : "com.fasterxml.jackson.core",
      "module" : "jackson-core",
      "version" : {
        "requires" : "2.13.0"
      }
    }, {
      "group" : "com.fasterxml.jackson.core",
      "module" : "jackson-databind",
      "version" : {
        "requires" : "2.13.0"
      }
    }, {
      "group" : "com.google.code.findbugs",
      "module" : "jsr305",
      "version" : {
        "requires" : "3.0.2"
      }
    }, {
      "group" : "com.google.common",
      "module" : "google-collect",
      "version" : {
        "requires" : "0.5"
      }
    }, {
      "group" : "javax.activation",
      "module" : "activation",
      "version" : {
        "requires" : "1.1.1"
      }
    }, {
      "group" : "javax.xml.bind",
      "module" : "jaxb-api",
      "version" : {
        "requires" : "2.4.0-b180830.0359"
      }
    }, {
      "group" : "log4j",
      "module" : "log4j",
      "version" : {
        "requires" : "1.2.17"
      }
    }, {
      "group" : "org.msgpack",
      "module" : "jackson-dataformat-msgpack",
      "version" : {
        "requires" : "0.9.0"
      }
    } ],
    "files" : [ {
      "name" : "adf-core-java-master-SNAPSHOT.jar",
      "url" : "adf-core-java-master-SNAPSHOT.jar",
      "size" : 369142,
      "sha512" : "268dc76d6c2db1b9b1c54cbbf9febfd92e30c7c30753117fb82108e42501179a5d5668049ca117bd1ae2b0574873f3bf8eccd5e7d69a574999a2a974197d7f4b",
      "sha256" : "5fe29ce554d90bc278814e29e281b6e4fa1a935ec631640bc1aaf989e8615af8",
      "sha1" : "e2d8ebc437c857da19386381c516299888e94471",
      "md5" : "485d6dae40ec2e02e63fb36b0e1296a9"
    } ]
  } ]
}